global:
  host: "spidybox.home"
  localStorageRootPath: "/data/pouetpouet"
  defaultReplica: &defaultReplica 1
  defaultMaxMemory: &defaultMaxMemory "1024Mi"
  defaultMaxCpu: &defaultMaxCpu "500m"

  nfsVolume:
    name: "nfs"
    enabled: true
    path: "/volume1/medias"
    server: "192.168.1.2"
    capacity: 1Gi
    readOnly: false

# Open VPN client to use
openvpn:
  name: "openvpn"
  enabled: true
  debug: true
  image: openvpn/openvpn-as
  version: latest
  replicas: *defaultReplica
  netadmin: true
#  init:
#    image: "busybox"
#    version: "latest"
#    commands:
#      - "sh"
#      - "-c"
#      - "echo The app is running! && sleep 10 "
  probes:
    commands:
      - "/bin/bash"
      - "-c"
      - "ps -ef | grep openvpn*"
#      - "nc"
#      - "-u"
#      - "-z"
#      - "127.0.0.1"
#      - "1194"
  resources:
    limits:
      memory: *defaultMaxMemory
      cpu: *defaultMaxCpu
  ports:
    - name: "https"
      port: 443
      nodePort: 30443
    - name: "admin"
      port: 943
      nodePort: 30943
      ingressPath: "/vpn"
    - name: "vpn"
      port: 1194
      nodePort: 31194
      protocol: "UDP"
  volumes:
    - name: "openvpn"
      capacity: 1Gi

transmission:
  name: "transmission"
  enabled: true
  image: linuxserver/transmission
  version: latest
  replicas: 1
  resources:
    limits:
      memory: *defaultMaxMemory
      cpu: *defaultMaxCpu
  ports:
    - name: "http"
      port: 9091
      nodePort: 30091
      ingressPath: "/transmission"
  volumes:
    - name: config
      capacity: 1Gi
    - name: downloads
      capacity: 1Gi
#    - name: nas-medias-nfs-volume
#      capacity: 1Gi
#      claimName: nfs-pvc
#      accessMode: ReadWriteMany

prowlarr:
  name: "prowlarr"
  enabled: true
  image: linuxserver/prowlarr
  version: latest
  replicas: 1
  resources:
    limits:
      memory: 1Gi
      cpu: 2000m
  ports:
    - name: "http"
      port: 9696
      nodePort: 30096
      ingressPath: "/prowlarr"
  volumes:
    - name: config
      capacity: 1Gi
    - name: downloads
      capacity: 1Gi

sonarr:
  name: "sonarr"
  enabled: true
  image: linuxserver/sonarr
  version: latest
  replicas: 1
  resources:
    limits:
      memory: *defaultMaxMemory
      cpu: *defaultMaxCpu
  ports:
    - name: "http"
      port: 8989
      nodePort: 30089
      ingressPath: "/sonarr"
  volumes:
    - name: config
      capacity: 1Gi
    - name: downloads
      capacity: 1Gi
#    - name: tvshows
#      capacity: 1Gi
#      claimName: nfs-pvc
#      accessMode: ReadWriteMany
#      subPath: "/TV Shows"


lidarr:
  name: "lidarr"
  enabled: true
  image: linuxserver/lidarr
  version: latest
  replicas: 1
  resources:
    limits:
      memory: *defaultMaxMemory
      cpu: *defaultMaxCpu
  ports:
    - name: "http"
      port: 8686
      nodePort: 30086
      ingressPath: "/lidarr"
  volumes:
    - name: config
      capacity: 1Gi
    - name: downloads
      capacity: 1Gi

radarr:
  name: "radarr"
  enabled: true
  image: linuxserver/radarr
  version: latest
  replicas: 1
  resources:
    limits:
      memory: *defaultMaxMemory
      cpu: *defaultMaxCpu
  ports:
    - name: "http"
      port: 7878
      nodePort: 30078
      ingressPath: "/radarr"
  volumes:
    - name: config
      capacity: 1Gi
    - name: downloads
      capacity: 1Gi