---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: lidarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: lidarr-config-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: lidarr-downloads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: lidarr-downloads-pv
  resources:
    requests:
      storage: 10Gi
