---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: sonarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: spidybox-volume
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: sonarr-downloads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: spidybox-volume
  resources:
    requests:
      storage: 10Gi
