---
apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: prowlarr
spec:
  type: NodePort
  ports:
    - port: 9696
      targetPort: 9696
      nodePort: 30096
  selector:
    app: prowlarr