{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ $.Release.Namespace }}"
  name: "{{ .Values.name }}-dep"
  labels:
    app: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: "{{ .Values.name }}-app"
          image: {{ .Values.image }}:{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          ports:
            {{- range $port := .Values.ports }}
            - containerPort: {{ $port }}
            {{- end }}
{{/*          env:*/}}
{{/*            - name: PUID*/}}
{{/*              value: "1000"*/}}
{{/*            - name: PGID*/}}
{{/*              value: "1000"*/}}
          volumeMounts:
            {{- range $volume := .Values.volumes }}
            - name: "{{ $volume.name }}"
              mountPath: "/{{ $volume.name }}"
            {{- end }}
      volumes:
        {{- range $volume := .Values.volumes }}
        - name: "{{ $volume.name }}"
          persistentVolumeClaim:
            claimName: "{{ $volume.name }}-pvc"
        {{- end }}

{{- end }}