{{- define "secret" }}
{{ if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-sec"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "spidybox.labels" . | nindent 4 }}

data: |
  {{ toYaml .Values.se | indent 8 }}
{{- end }}
{{- end }}