{{- define "secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-sec"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "spidybox.labels" . | nindent 4 }}
data:

{{- end }}