apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{{ $.Release.Namespace }}"
  name: "{{ $.Release.Namespace }}-ingress"
spec:
  ingressClassName: "traefik"
  rules:
    - host: "{{ $.Values.global.host }}"
      http:
        paths:
          {{ range $v := .Values }}
          {{- if $v.name }}
          {{ range $p := $v.ports }}
          {{- if $p.ingressPath }}
          - path: "{{ $p.ingressPath }}"
            pathType: Prefix
            backend:
              service:
                name: "{{ $v.name }}-svc"
                port:
                  name: "{{ $p.name }}"
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
